services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: recon-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_PID: "Developer"
    ports:
      - "14330:1433"
    volumes:
      - recon-sqldata:/var/opt/mssql

volumes:
  recon-sqldata:
