@host = http://localhost:5075

### List all tenants (empty at first)
GET {{host}}/api/tenants

### Create a tenant
POST {{host}}/api/tenants
Content-Type: application/json

{
  "name": "Fajr Investment",
  "code": "fajr"
}

### Try a bad one (should fail validation)
POST {{host}}/api/tenants
Content-Type: application/json

{
  "name": "",
  "code": "fajr11"
}